// Initially Created by: Devin Brueberg
// 2022 Side Project
// Gold-Briefing - constants.js
// November 17, 2023
// Last Edited (Initials, Date, Edits):
//  (DAB, 05/10/2025, Added in isLoading constants)

// The constants.js page will allow error free use of
// commonly used and connected key functionality
export const reduxAction = {
    ADD_ACKNOWLEDGEMENT: "ADD_ACKNOWLEDGMENT",
    UPDATE_ACKNOWLEDGEMENT: "UPDATE_ACKNOWLEDGMENT",
    DELETE_ACKNOWLEDGEMENT: "DELETE_ACKNOWLEDGMENT",
    DELETE_ALL_ACKNOWLEDGEMENTS: "DELETE_ALL_ACKNOWLEDGMENTS",

    ADD_ALL_BRIEFING_LIST: "ADD_ALL_BRIEFING_LIST",
    ADD_BRIEFING_LIST: "ADD_BRIEFING_LIST",
    UPDATE_BRIEFING_LIST: "UPDATE_BRIEFING_LIST",
    DELETE_BRIEFING_LIST: "DELETE_BRIEFING_LIST",
    DELETE_ALL_BRIEFING_LIST: "DELETE_ALL_BRIEFING_LIST",

    ADD_EMERGENCY_PLAN: "ADD_EMERGENCY_PLAN",
    UPDATE_EMERGENCY_PLAN: "UPDATE_EMERGENCY_PLAN",
    DELETE_EMERGENCY_PLAN: "DELETE_EMERGENCY_PLAN",
    DELETE_ALL_EMERGENCY_PLAN: "DELETE_ALL_EMERGENCY_PLAN",

    ADD_USER: "ADD_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",
    DELETE_ALL_USER: "DELETE_ALL_USER",

    ADD_JOB_BRIEFING: "ADD_JOB_BRIEFING",
    UPDATE_JOB_BRIEFING: "UPDATE_JOB_BRIEFING",
    DELETE_JOB_BRIEFING: "DELETE_JOB_BRIEFING",
    DELETE_ALL_JOB_BRIEFING: "DELETE_ALL_JOB_BRIEFING",

    ADD_GENERAL: "ADD_GENERAL",
    UPDATE_GENERAL: "UPDATE_GENERAL",
    DELETE_GENERAL: "DELETE_GENERAL",
    DELETE_ALL_GENERAL: "DELETE_ALL_GENERAL",

    ADD_WEATHER: "ADD_WEATHER",
    UPDATE_WEATHER: "UPDATE_WEATHER",
    DELETE_WEATHER: "DELETE_WEATHER",
    DELETE_ALL_WEATHER: "DELETE_ALL_WEATHER",

    START_LOADING_BRIEFING_UPDATE: "START_LOADING_BRIEFING_UPDATE",
    START_LOADING_BRIEFING_CREATE: "START_LOADING_BRIEFING_CREATE",
    START_LOADING_CREATE_ACCOUNT: "START_LOADING_CREATE_ACCOUNT",
    START_LOADING_DELETE_BRIEFING: "START_LOADING_DELETE_BRIEFING",
    START_LOADING_LOGGING_IN: "START_LOADING_LOGGING_IN",
    START_LOADING_LOAD_BRIEFING: "START_LOADING_LOAD_BRIEFING",
    END_LOADING_BRIEFING_UPDATE: "END_LOADING_BRIEFING_UPDATE",
    END_LOADING_BRIEFING_CREATE: "END_LOADING_BRIEFING_CREATE",
    END_LOADING_CREATE_ACCOUNT: "END_LOADING_CREATE_ACCOUNT",
    END_LOADING_DELETE_BRIEFING: "END_LOADING_DELETE_BRIEFING",
    END_LOADING_LOGGING_IN: "END_LOADING_LOGGING_IN",
    END_LOADING_LOAD_BRIEFING: "END_LOADING_LOAD_BRIEFING",
    END_LOADING_ALL: "END_LOADING_ALL",
};

export const exposureConstants = {
    LIFE_SAVING_NAME: "Life Saving Processes",
    LINE_FIRE_NAME: "Line of Fire/Release of Energy",
    PINCH_POINT_NAME: "Pinch Points",
    ASC_DESC_NAME: "Ascending/Descending",
    PATH_TRAVEL_NAME: "Walking/Path of Travel",
};
