// Initially Created by: Devin Brueberg
// 2022 Side Project
// Gold-Briefing - constants.js
// November 17, 2023
// Last Edited (Initials, Date, Edits):

// The constants.js page will allow error free use of 
// commonly used and connected key functionality
export const reduxAction = {
    ADD_ACKNOWLEDGEMENT: "ADD_ACKNOWLEDGMENT",
    UPDATE_ACKNOWLEDGEMENT: "UPDATE_ACKNOWLEDGMENT",
    DELETE_ACKNOWLEDGEMENT: "DELETE_ACKNOWLEDGMENT",
    DELETE_ALL_ACKNOWLEDGEMENT: "DELETE_ALL_ACKNOWLEDGMENT",

    ADD_BRIEFING_LIST: "ADD_BRIEFING_LIST",
    UPDATE_BRIEFING_LIST: "UPDATE_BRIEFING_LIST",
    DELETE_BRIEFING_LIST: "DELETE_BRIEFING_LIST",
    DELETE_ALL_BRIEFING_LIST: "DELETE_ALL_BRIEFING_LIST",

    ADD_EMERGENCY_PLAN: "ADD_EMERGENCY_PLAN",
    UPDATE_EMERGENCY_PLAN: "UPDATE_EMERGENCY_PLAN",
    DELETE_EMERGENCY_PLAN: "DELETE_EMERGENCY_PLAN",
    DELETE_ALL_EMERGENCY_PLAN: "DELETE_ALL_EMERGENCY_PLAN",

    ADD_USER: "ADD_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER:"DELETE_USER",
    DELETE_ALL_USER: "DELETE_ALL_USER",

    ADD_JOB_BRIEFING: "ADD_JOB_BRIEFING",
    UPDATE_JOB_BRIEFING: "UPDATE_JOB_BRIEFING",
    DELETE_JOB_BRIEFING: "DELETE_JOB_BRIEFING",
    DELETE_ALL_JOB_BRIEFING: "DELETE_ALL_JOB_BRIEFING",

    ADD_GENERAL: "ADD_GENERAL",
    UPDATE_GENERAL: "UPDATE_GENERAL",
    DELETE_GENERAL: "DELETE_GENERAL",
    DELETE_ALL_GENERAL: "DELETE_ALL_GENERAL",

    ADD_WEATHER: "ADD_WEATHER",
    UPDATE_WEATHER: "UPDATE_WEATHER",
    DELETE_WEATHER: "DELETE_WEATHER",
    DELETE_ALL_WEATHER: "DELETE_ALL_WEATHER",
};
